<a href="https://colab.research.google.com/github/shraddhakawalkar4-glitch/session15-special-Task-/blob/main/sample_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Among us.csv to Among us.csv

In [ ]:
filepath="/content/Among us.csv"
df=pd.read_csv(filepath)

In [ ]:
df

,Game Completed Date,Team,Outcome,Task Completed,All Tasks Completed,Murdered,Imposter Kills,Game Length,Ejected,Sabotages Fixed,Time to complete all tasks,Rank Change,Region/Game Code
0,12/13/2020 at 1:26:56 am EST,Crewmate,Win,3,No,Yes,-,07m 04s,No,2.0,-,++,NA / WYMSBF
1,12/13/2020 at 1:17:42 am EST,Crewmate,Loss,7,Yes,No,-,16m 21s,No,1.0,09m 48s,--,NA / WYMSBF
2,12/13/2020 at 12:57:47 am EST,Crewmate,Win,3,No,No,-,11m 33s,No,0.0,-,++,NA / WYMSBF
3,12/13/2020 at 12:41:55 am EST,Imposter,Win,-,-,-,2,08m 05s,No,NaN,-,+++,Europe / QIRTNF
4,12/13/2020 at 12:30:37 am EST,Crewmate,Loss,4,No,No,-,05m 10s,No,0.0,-,---,Europe / QIRTNF
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12/06/2020 at 12:43:22 am EST,Crewmate,Win,8,Yes,Yes,-,11m 29s,No,0.0,05m 01s,++,Europe / RUFQCF
96,12/06/2020 at 12:27:10 am EST,Crewmate,Win,8,Yes,No,-,11m 31s,No,0.0,05m 45s,++,Europe / RUFQCF
97,12/06/2020 at 12:14:34 am EST,Crewmate,Win,8,Yes,No,-,10m 36s,No,0.0,06m 55s,++,Europe / RUFQCF
98,12/06/2020 at 12:02:37 am EST,Crewmate,Loss,8,Yes,Yes,-,11m 12s,No,0.0,07m 43s,--,Europe / RUFQCF
99,12/05/2020 at 11:45:54 pm EST,Imposter,Win,-,-,-,4,21m 23s,No,NaN,-,+++,Europe / RUFQCF

In [ ]:
df.head()

,Game Completed Date,Team,Outcome,Task Completed,All Tasks Completed,Murdered,Imposter Kills,Game Length,Ejected,Sabotages Fixed,Time to complete all tasks,Rank Change,Region/Game Code
0,12/13/2020 at 1:26:56 am EST,Crewmate,Win,3,No,Yes,-,07m 04s,No,2.0,-,++,NA / WYMSBF
1,12/13/2020 at 1:17:42 am EST,Crewmate,Loss,7,Yes,No,-,16m 21s,No,1.0,09m 48s,--,NA / WYMSBF
2,12/13/2020 at 12:57:47 am EST,Crewmate,Win,3,No,No,-,11m 33s,No,0.0,-,++,NA / WYMSBF
3,12/13/2020 at 12:41:55 am EST,Imposter,Win,-,-,-,2,08m 05s,No,NaN,-,+++,Europe / QIRTNF
4,12/13/2020 at 12:30:37 am EST,Crewmate,Loss,4,No,No,-,05m 10s,No,0.0,-,---,Europe / QIRTNF

In [ ]:
df.tail()

,Game Completed Date,Team,Outcome,Task Completed,All Tasks Completed,Murdered,Imposter Kills,Game Length,Ejected,Sabotages Fixed,Time to complete all tasks,Rank Change,Region/Game Code
95,12/06/2020 at 12:43:22 am EST,Crewmate,Win,8,Yes,Yes,-,11m 29s,No,0.0,05m 01s,++,Europe / RUFQCF
96,12/06/2020 at 12:27:10 am EST,Crewmate,Win,8,Yes,No,-,11m 31s,No,0.0,05m 45s,++,Europe / RUFQCF
97,12/06/2020 at 12:14:34 am EST,Crewmate,Win,8,Yes,No,-,10m 36s,No,0.0,06m 55s,++,Europe / RUFQCF
98,12/06/2020 at 12:02:37 am EST,Crewmate,Loss,8,Yes,Yes,-,11m 12s,No,0.0,07m 43s,--,Europe / RUFQCF
99,12/05/2020 at 11:45:54 pm EST,Imposter,Win,-,-,-,4,21m 23s,No,NaN,-,+++,Europe / RUFQCF

In [ ]:
df.shape

(100, 13)

In [ ]:
df.columns

Index(['Game Completed Date', 'Team', 'Outcome', 'Task Completed',
       'All Tasks Completed', 'Murdered', 'Imposter Kills', 'Game Length',
       'Ejected', 'Sabotages Fixed', 'Time to complete all tasks',
       'Rank Change', 'Region/Game Code'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Game Completed Date         100 non-null    object
 1   Team                        100 non-null    object
 2   Outcome                     100 non-null    object
 3   Task Completed              100 non-null    object
 4   All Tasks Completed         100 non-null    object
 5   Murdered                    100 non-null    object
 6   Imposter Kills              100 non-null    object
 7   Game Length                 100 non-null    object
 8   Ejected                     100 non-null    object
 9   Sabotages Fixed             77 non-null     float64
 10  Time to complete all tasks  100 non-null    object
 11  Rank Change                 92 non-null     object
 12  Region/Game Code            100 non-null    object
dtypes: float64(1), object(12)
memory usage: 10.3+ KB

In [ ]:
df.describe()

       Sabotages Fixed
count        77.000000
mean          0.389610
std           0.631536
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           3.000000

In [ ]:
df.dtypes

Game Completed Date            object
Team                           object
Outcome                        object
Task Completed                 object
All Tasks Completed            object
Murdered                       object
Imposter Kills                 object
Game Length                    object
Ejected                        object
Sabotages Fixed               float64
Time to complete all tasks     object
Rank Change                    object
Region/Game Code               object
dtype: object

In [ ]:
df.isnull().sum()

Game Completed Date            0
Team                           0
Outcome                        0
Task Completed                 0
All Tasks Completed            0
Murdered                       0
Imposter Kills                 0
Game Length                    0
Ejected                        0
Sabotages Fixed               23
Time to complete all tasks     0
Rank Change                    8
Region/Game Code               0
dtype: int64

In [ ]:
df.nunique()

Game Completed Date           100
Team                            2
Outcome                         2
Task Completed                  9
All Tasks Completed             3
Murdered                        3
Imposter Kills                  7
Game Length                    95
Ejected                         2
Sabotages Fixed                 4
Time to complete all tasks     41
Rank Change                     5
Region/Game Code               22
dtype: int64

In [ ]:
df.sample(5)

,Game Completed Date,Team,Outcome,Task Completed,All Tasks Completed,Murdered,Imposter Kills,Game Length,Ejected,Sabotages Fixed,Time to complete all tasks,Rank Change,Region/Game Code
98,12/06/2020 at 12:02:37 am EST,Crewmate,Loss,8,Yes,Yes,-,11m 12s,No,0.0,07m 43s,--,Europe / RUFQCF
20,12/11/2020 at 12:29:51 am EST,Crewmate,Loss,2,No,Yes,-,14m 43s,No,0.0,-,---,NA / EYNONF
58,12/08/2020 at 9:47:41 pm EST,Imposter,Loss,-,-,-,1,01m 28s,Yes,NaN,-,NaN,Europe / RLNKUF
80,12/06/2020 at 9:52:44 pm EST,Crewmate,Win,8,Yes,Yes,-,17m 20s,No,0.0,04m 59s,++,NA / JKQLUF
31,12/10/2020 at 12:30:51 am EST,Imposter,Loss,-,-,-,1,02m 35s,Yes,NaN,-,NaN,Europe / KTQRWQ

In [ ]:
df.value_counts()

Game Completed Date            Team      Outcome  Task Completed  All Tasks Completed  Murdered  Imposter Kills  Game Length  Ejected  Sabotages Fixed  Time to complete all tasks  Rank Change  Region/Game Code
12/06/2020 at 12:02:37 am EST  Crewmate  Loss     8               Yes                  Yes       -               11m 12s      No       0.0              07m 43s                     --           Europe / RUFQCF     1
12/06/2020 at 12:14:34 am EST  Crewmate  Win      8               Yes                  No        -               10m 36s      No       0.0              06m 55s                     ++           Europe / RUFQCF     1
12/06/2020 at 12:27:10 am EST  Crewmate  Win      8               Yes                  No        -               11m 31s      No       0.0              05m 45s                     ++           Europe / RUFQCF     1
12/06/2020 at 12:43:22 am EST  Crewmate  Win      8               Yes                  Yes       -               11m 29s      No       0.0              05m 01s                     ++           Europe / RUFQCF     1
12/06/2020 at 12:55:57 am EST  Crewmate  Loss     7               No                   Yes       -               11m 40s      No       1.0              -                           ---          Europe / RUFQCF     1
                                                                                                                                                                                                                    ..
12/13/2020 at 12:24:20 am EST  Crewmate  Loss     7               Yes                  Yes       -               16m 22s      No       0.0              12m 16s                     --           Europe / QIRTNF     1
12/13/2020 at 12:30:37 am EST  Crewmate  Loss     4               No                   No        -               05m 10s      No       0.0              -                           ---          Europe / QIRTNF     1
12/13/2020 at 12:57:47 am EST  Crewmate  Win      3               No                   No        -               11m 33s      No       0.0              -                           ++           NA / WYMSBF         1
12/13/2020 at 1:17:42 am EST   Crewmate  Loss     7               Yes                  No        -               16m 21s      No       1.0              09m 48s                     --           NA / WYMSBF         1
12/13/2020 at 1:26:56 am EST   Crewmate  Win      3               No                   Yes       -               07m 04s      No       2.0              -                           ++           NA / WYMSBF         1
Name: count, Length: 73, dtype: int64